spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s



bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /upload.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your limit requests \" }"
      rate-limits:
        - expression: "@securityService.username()"
          bandwidths:
            - capacity: 25
              time: 1
              unit: hours
        - expression: "getRemoteAddr()"
          bandwidths:
            - capacity: 40
              time: 1
              unit: hours
